spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/atelie
    username: atelie
    password: atelie123
    driver-class-name: org.postgresql.Driver

jwt:
  secret: "uma-chave-secreta-local-do-atelie-ritalara-2026"